language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

#before_install:
# - chmod +x gradlew

script:
  - mvn clean package -DskipTests=true

after_success:
  - cd ./target
  - git init
  - git config user.name "1661788089@qq.com"
  - git config user.email "1661788089@qq.com"
  - git add helloworld-0.0.1-SNAPSHOT.jar
  - git commit -m "version 1"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - test

notifications:
  email: false

env:
  global:
    - GH_REF=github.com/1661788089/testproject0331.git
